language: node_js
node_js:
  - "12.8.3"

sudo: required

services:
  - docker

before_install:
  - docker build -t frontend-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true frontend-react-app npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-2-612536521820"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY_DOCKER_REACT"
  secret_access_key:
    secure: "$AWS_SECRET_KEY_DOCKER_REACT"



